#!/bin/bash

# Создание директории
mkdir MyDirectory

# Переход в директорию
cd MyDirectory

# Создание файла
touch MyFile.txt

# Возврат в исходный каталог и вывод списка файлов и директорий
cd ..
ls
